### ISSUE TITLE
Carousel is broken in android.

### ISSUE THREAD

**Issue by nis24jit** [nick/react-native-carousel#32]
The carousel is broken in android.The swiping is not working properly in android.

**Comment by RussMax783** [comment]
It is pretty broken in Android... 

If user swipes at all, then it acts as a normal scroll view with out any locking screen by screen.
![screen shot 2016-02-09 at 10 30 45 am](https://cloud.githubusercontent.com/assets/5333786/12924637/532f3664-cf18-11e5-8407-ec2d077cc590.png)

For my particular use case, It also starts on the last page and cycles through once, until it gets to the first page, then stops scrolling any further. I can scroll back, but again it doesn't lock.

**Comment by dangnelson** [comment]
+1

**Comment by stianmartinsen** [comment]
+ 1. The carousel doesn't snap to the individual slides when swiping, and the indicators aren't updated. Clicking the indicators works as expected. Would love to see a fix.
