### ISSUE TITLE
How to adapt width to device size?

### ISSUE THREAD

**Issue by mecmuc** [nick/react-native-carousel#78]
Should I use a constant width like 375 in the example or how can I adapt the width to the different device sizes? 
In android flex:1 seems to work, but not in iOS.

**Comment by vanderstelTroy** [comment]
let ScreenWidth = Dimensions.get('window').width;

<Carousel width={Dimensions.get('window').width}> </Carousel>

slideCssClassName: {
  width: ScreenWidth,
  flex:1,
  justifyContent: 'center',
  alignItems: 'center',
}
